//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.PoskytnutieUdajovIFOOnlineWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TPOD pODField;

        private string corrIDField;

        /// <remarks/>
        public TPOD POD
        {
            get
            {
                return this.pODField;
            }
            set
            {
                this.pODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TPOD
    {

        private TIOS[] iOSListField;

        private TUES uESField;

        private TSPI_SPN[] sPIListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IOS", IsNullable = false)]
        public TIOS[] IOSList
        {
            get
            {
                return this.iOSListField;
            }
            set
            {
                this.iOSListField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SPI", IsNullable = false)]
        public TSPI_SPN[] SPIList
        {
            get
            {
                return this.sPIListField;
            }
            set
            {
                this.sPIListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TIOS
    {

        private string ifField;

        /// <remarks/>
        public string IF
        {
            get
            {
                return this.ifField;
            }
            set
            {
                this.ifField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TZUD_ZUNO
    {

        private int zoField;

        private string zOBZONAField;

        private int idField;

        /// <remarks/>
        public int ZO
        {
            get
            {
                return this.zoField;
            }
            set
            {
                this.zoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ZOBZONA
        {
            get
            {
                return this.zOBZONAField;
            }
            set
            {
                this.zOBZONAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TSNR_SNPO
    {

        private int snField;

        private string sNPSNNAField;

        private System.Nullable<System.DateTime> dzField;

        private System.Nullable<System.DateTime> dkField;

        private string pzField;

        private int idField;

        /// <remarks/>
        public int SN
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }

        /// <remarks/>
        public string SNPSNNA
        {
            get
            {
                return this.sNPSNNAField;
            }
            set
            {
                this.sNPSNNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PZ
        {
            get
            {
                return this.pzField;
            }
            set
            {
                this.pzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TUSOO
    {

        private System.Nullable<System.DateTime> dpField;

        private System.Nullable<bool> udField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> UD
        {
            get
            {
                return this.udField;
            }
            set
            {
                this.udField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TDCD_DCIO
    {

        private int ddField;

        private string dDCDDNAField;

        private string cdField;

        private bool duField;

        private int idField;

        /// <remarks/>
        public int DD
        {
            get
            {
                return this.ddField;
            }
            set
            {
                this.ddField = value;
            }
        }

        /// <remarks/>
        public string DDCDDNA
        {
            get
            {
                return this.dDCDDNAField;
            }
            set
            {
                this.dDCDDNAField = value;
            }
        }

        /// <remarks/>
        public string CD
        {
            get
            {
                return this.cdField;
            }
            set
            {
                this.cdField = value;
            }
        }

        /// <remarks/>
        public bool DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TPZMO
    {

        private System.Nullable<System.DateTime> dpField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TZPZO
    {

        private int ucField;

        private string uCEUCNAField;

        private int idField;

        /// <remarks/>
        public int UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TZPOO
    {

        private System.Nullable<System.DateTime> dzField;

        private System.Nullable<System.DateTime> dkField;

        private string poField;

        private TZPZO[] zPZListField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZPZ", IsNullable = false)]
        public TZPZO[] ZPZList
        {
            get
            {
                return this.zPZListField;
            }
            set
            {
                this.zPZListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TREGO
    {

        private int poField;

        private string reField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string RE
        {
            get
            {
                return this.reField;
            }
            set
            {
                this.reField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TPOB_PHRO
    {

        private int tpField;

        private string tbField;

        private System.Nullable<System.DateTime> dpField;

        private System.Nullable<System.DateTime> duField;

        private string noField;

        private System.Nullable<int> scField;

        private string ncField;

        private string nkField;

        private string nuField;

        private System.Nullable<int> stField;

        private string nsField;

        private string mpField;

        private string opField;

        private string ooField;

        private string ccField;

        private string umField;

        private string osField;

        private string siField;

        private string cuField;

        private bool pmField;

        private string pcField;

        private string cbField;

        private string iaField;

        private System.Nullable<int> vdField;

        private bool vdFieldSpecified;

        private System.Nullable<int> diField;

        private bool diFieldSpecified;

        private System.Nullable<int> uiField;

        private bool uiFieldSpecified;

        private System.Nullable<int> ceField;

        private bool ceFieldSpecified;

        private System.Nullable<int> oaField;

        private bool oaFieldSpecified;

        private System.Nullable<int> ueField;

        private bool ueFieldSpecified;

        private string olField;

        private TREGO[] rEGListField;

        private int idField;

        /// <remarks/>
        public int TP
        {
            get
            {
                return this.tpField;
            }
            set
            {
                this.tpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TB
        {
            get
            {
                return this.tbField;
            }
            set
            {
                this.tbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NO
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SC
        {
            get
            {
                return this.scField;
            }
            set
            {
                this.scField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NC
        {
            get
            {
                return this.ncField;
            }
            set
            {
                this.ncField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NS
        {
            get
            {
                return this.nsField;
            }
            set
            {
                this.nsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MP
        {
            get
            {
                return this.mpField;
            }
            set
            {
                this.mpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OP
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OO
        {
            get
            {
                return this.ooField;
            }
            set
            {
                this.ooField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OS
        {
            get
            {
                return this.osField;
            }
            set
            {
                this.osField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CU
        {
            get
            {
                return this.cuField;
            }
            set
            {
                this.cuField = value;
            }
        }

        /// <remarks/>
        public bool PM
        {
            get
            {
                return this.pmField;
            }
            set
            {
                this.pmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PC
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CB
        {
            get
            {
                return this.cbField;
            }
            set
            {
                this.cbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IA
        {
            get
            {
                return this.iaField;
            }
            set
            {
                this.iaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> VD
        {
            get
            {
                return this.vdField;
            }
            set
            {
                this.vdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VDSpecified
        {
            get
            {
                return this.vdFieldSpecified;
            }
            set
            {
                this.vdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DI
        {
            get
            {
                return this.diField;
            }
            set
            {
                this.diField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DISpecified
        {
            get
            {
                return this.diFieldSpecified;
            }
            set
            {
                this.diFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UI
        {
            get
            {
                return this.uiField;
            }
            set
            {
                this.uiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UISpecified
        {
            get
            {
                return this.uiFieldSpecified;
            }
            set
            {
                this.uiFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> CE
        {
            get
            {
                return this.ceField;
            }
            set
            {
                this.ceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CESpecified
        {
            get
            {
                return this.ceFieldSpecified;
            }
            set
            {
                this.ceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> OA
        {
            get
            {
                return this.oaField;
            }
            set
            {
                this.oaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OASpecified
        {
            get
            {
                return this.oaFieldSpecified;
            }
            set
            {
                this.oaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UESpecified
        {
            get
            {
                return this.ueFieldSpecified;
            }
            set
            {
                this.ueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OL
        {
            get
            {
                return this.olField;
            }
            set
            {
                this.olField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("REG", IsNullable = false)]
        public TREGO[] REGList
        {
            get
            {
                return this.rEGListField;
            }
            set
            {
                this.rEGListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TRVE_RVXO
    {

        private string ifField;

        private int trField;

        private string tRZTRNAField;

        private System.Nullable<System.DateTime> dvField;

        private string mvField;

        private System.Nullable<int> ucField;

        private string uCEUCNAField;

        private System.Nullable<int> tlField;

        private string tRRTLNAField;

        private System.Nullable<int> teField;

        private string tRRTENAField;

        private string smField;

        private System.Nullable<int> paField;

        private bool paFieldSpecified;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IF
        {
            get
            {
                return this.ifField;
            }
            set
            {
                this.ifField = value;
            }
        }

        /// <remarks/>
        public int TR
        {
            get
            {
                return this.trField;
            }
            set
            {
                this.trField = value;
            }
        }

        /// <remarks/>
        public string TRZTRNA
        {
            get
            {
                return this.tRZTRNAField;
            }
            set
            {
                this.tRZTRNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DV
        {
            get
            {
                return this.dvField;
            }
            set
            {
                this.dvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MV
        {
            get
            {
                return this.mvField;
            }
            set
            {
                this.mvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> TL
        {
            get
            {
                return this.tlField;
            }
            set
            {
                this.tlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TRRTLNA
        {
            get
            {
                return this.tRRTLNAField;
            }
            set
            {
                this.tRRTLNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> TE
        {
            get
            {
                return this.teField;
            }
            set
            {
                this.teField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TRRTENA
        {
            get
            {
                return this.tRRTENAField;
            }
            set
            {
                this.tRRTENAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SM
        {
            get
            {
                return this.smField;
            }
            set
            {
                this.smField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PASpecified
        {
            get
            {
                return this.paFieldSpecified;
            }
            set
            {
                this.paFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TSPR_SPIO
    {

        private string sTASTNAField;

        private int stField;

        private int idField;

        /// <remarks/>
        public string STASTNA
        {
            get
            {
                return this.sTASTNAField;
            }
            set
            {
                this.sTASTNAField = value;
            }
        }

        /// <remarks/>
        public int ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TTOS_TOIO
    {

        private string tITTINAField;

        private string tTITTNAField;

        private int tiField;

        private int ttField;

        private System.Nullable<System.DateTime> frField;

        private int idField;

        /// <remarks/>
        public string TITTINA
        {
            get
            {
                return this.tITTINAField;
            }
            set
            {
                this.tITTINAField = value;
            }
        }

        /// <remarks/>
        public string TTITTNA
        {
            get
            {
                return this.tTITTNAField;
            }
            set
            {
                this.tTITTNAField = value;
            }
        }

        /// <remarks/>
        public int TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }

        /// <remarks/>
        public int TT
        {
            get
            {
                return this.ttField;
            }
            set
            {
                this.ttField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> FR
        {
            get
            {
                return this.frField;
            }
            set
            {
                this.frField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TRPRO
    {

        private int poField;

        private string rpField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RP
        {
            get
            {
                return this.rpField;
            }
            set
            {
                this.rpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TPRIO
    {

        private int poField;

        private string prField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PR
        {
            get
            {
                return this.prField;
            }
            set
            {
                this.prField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TMOSO
    {

        private string meField;

        private int poField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ME
        {
            get
            {
                return this.meField;
            }
            set
            {
                this.meField = value;
            }
        }

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TOEX_OEIO
    {

        private string idField;

        private string poField;

        private string rcField;

        private System.Nullable<System.DateTime> dnField;

        private bool dnFieldSpecified;

        private System.Nullable<int> ucField;

        private bool ucFieldSpecified;

        private string uCEUCNAField;

        private string mnField;

        private System.Nullable<int> snField;

        private bool snFieldSpecified;

        private string sTASNNAField;

        private System.Nullable<int> piField;

        private bool piFieldSpecified;

        private string pOHPINAField;

        private System.Nullable<int> rsField;

        private bool rsFieldSpecified;

        private string rSTRSNAField;

        private string rmField;

        private System.Nullable<int> niField;

        private bool niFieldSpecified;

        private string nARNINAField;

        private System.Nullable<System.DateTime> duField;

        private bool duFieldSpecified;

        private System.Nullable<int> ueField;

        private bool ueFieldSpecified;

        private string uCEUENAField;

        private string muField;

        private string umField;

        private System.Nullable<int> suField;

        private bool suFieldSpecified;

        private string sTASUNAField;

        private string biField;

        private System.Nullable<int> tvField;

        private bool tvFieldSpecified;

        private string tVKTVNAField;

        private System.Nullable<int> ulField;

        private bool ulFieldSpecified;

        private string uCEULNAField;

        private System.Nullable<int> uoField;

        private bool uoFieldSpecified;

        private string uCEUONAField;

        private string icField;

        private System.Nullable<int> szField;

        private bool szFieldSpecified;

        private string sZVSZNAField;

        private System.Nullable<int> rnField;

        private bool rnFieldSpecified;

        private System.Nullable<System.DateTime> dkField;

        private bool dkFieldSpecified;

        private string dlField;

        private int nkField;

        private string dpField;

        private System.Nullable<int> paField;

        private bool paFieldSpecified;

        private System.Nullable<int> pgField;

        private bool pgFieldSpecified;

        private TMOSO[] mOSListField;

        private TPRIO[] pRIListField;

        private TRPRO[] rPRListField;

        private TTOS_TOIO[] tOSListField;

        private TSPR_SPIO[] sPRListField;

        private TRVE_RVXO[] rVEListField;

        private TPOB_PHRO[] pOBListField;

        private TZPOO[] zPOListField;

        private TPZMO[] pZMListField;

        private TDCD_DCIO[] dCDListField;

        private TUSOO[] uSOListField;

        private TSNR_SNPO[] sNRListField;

        private TZUD_ZUNO[] zUDListField;

        private int iD1Field;

        private bool iD1FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RC
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DN
        {
            get
            {
                return this.dnField;
            }
            set
            {
                this.dnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DNSpecified
        {
            get
            {
                return this.dnFieldSpecified;
            }
            set
            {
                this.dnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UCSpecified
        {
            get
            {
                return this.ucFieldSpecified;
            }
            set
            {
                this.ucFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MN
        {
            get
            {
                return this.mnField;
            }
            set
            {
                this.mnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SN
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNSpecified
        {
            get
            {
                return this.snFieldSpecified;
            }
            set
            {
                this.snFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string STASNNA
        {
            get
            {
                return this.sTASNNAField;
            }
            set
            {
                this.sTASNNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PI
        {
            get
            {
                return this.piField;
            }
            set
            {
                this.piField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PISpecified
        {
            get
            {
                return this.piFieldSpecified;
            }
            set
            {
                this.piFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string POHPINA
        {
            get
            {
                return this.pOHPINAField;
            }
            set
            {
                this.pOHPINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> RS
        {
            get
            {
                return this.rsField;
            }
            set
            {
                this.rsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSSpecified
        {
            get
            {
                return this.rsFieldSpecified;
            }
            set
            {
                this.rsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RSTRSNA
        {
            get
            {
                return this.rSTRSNAField;
            }
            set
            {
                this.rSTRSNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RM
        {
            get
            {
                return this.rmField;
            }
            set
            {
                this.rmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> NI
        {
            get
            {
                return this.niField;
            }
            set
            {
                this.niField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NISpecified
        {
            get
            {
                return this.niFieldSpecified;
            }
            set
            {
                this.niFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NARNINA
        {
            get
            {
                return this.nARNINAField;
            }
            set
            {
                this.nARNINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DUSpecified
        {
            get
            {
                return this.duFieldSpecified;
            }
            set
            {
                this.duFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UESpecified
        {
            get
            {
                return this.ueFieldSpecified;
            }
            set
            {
                this.ueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUENA
        {
            get
            {
                return this.uCEUENAField;
            }
            set
            {
                this.uCEUENAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MU
        {
            get
            {
                return this.muField;
            }
            set
            {
                this.muField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SU
        {
            get
            {
                return this.suField;
            }
            set
            {
                this.suField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUSpecified
        {
            get
            {
                return this.suFieldSpecified;
            }
            set
            {
                this.suFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string STASUNA
        {
            get
            {
                return this.sTASUNAField;
            }
            set
            {
                this.sTASUNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BI
        {
            get
            {
                return this.biField;
            }
            set
            {
                this.biField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> TV
        {
            get
            {
                return this.tvField;
            }
            set
            {
                this.tvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TVSpecified
        {
            get
            {
                return this.tvFieldSpecified;
            }
            set
            {
                this.tvFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TVKTVNA
        {
            get
            {
                return this.tVKTVNAField;
            }
            set
            {
                this.tVKTVNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UL
        {
            get
            {
                return this.ulField;
            }
            set
            {
                this.ulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ULSpecified
        {
            get
            {
                return this.ulFieldSpecified;
            }
            set
            {
                this.ulFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEULNA
        {
            get
            {
                return this.uCEULNAField;
            }
            set
            {
                this.uCEULNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UO
        {
            get
            {
                return this.uoField;
            }
            set
            {
                this.uoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UOSpecified
        {
            get
            {
                return this.uoFieldSpecified;
            }
            set
            {
                this.uoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUONA
        {
            get
            {
                return this.uCEUONAField;
            }
            set
            {
                this.uCEUONAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IC
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SZ
        {
            get
            {
                return this.szField;
            }
            set
            {
                this.szField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SZSpecified
        {
            get
            {
                return this.szFieldSpecified;
            }
            set
            {
                this.szFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SZVSZNA
        {
            get
            {
                return this.sZVSZNAField;
            }
            set
            {
                this.sZVSZNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> RN
        {
            get
            {
                return this.rnField;
            }
            set
            {
                this.rnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RNSpecified
        {
            get
            {
                return this.rnFieldSpecified;
            }
            set
            {
                this.rnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DKSpecified
        {
            get
            {
                return this.dkFieldSpecified;
            }
            set
            {
                this.dkFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DL
        {
            get
            {
                return this.dlField;
            }
            set
            {
                this.dlField = value;
            }
        }

        /// <remarks/>
        public int NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PASpecified
        {
            get
            {
                return this.paFieldSpecified;
            }
            set
            {
                this.paFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PG
        {
            get
            {
                return this.pgField;
            }
            set
            {
                this.pgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PGSpecified
        {
            get
            {
                return this.pgFieldSpecified;
            }
            set
            {
                this.pgFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MOS", IsNullable = false)]
        public TMOSO[] MOSList
        {
            get
            {
                return this.mOSListField;
            }
            set
            {
                this.mOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PRI", IsNullable = false)]
        public TPRIO[] PRIList
        {
            get
            {
                return this.pRIListField;
            }
            set
            {
                this.pRIListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RPR", IsNullable = false)]
        public TRPRO[] RPRList
        {
            get
            {
                return this.rPRListField;
            }
            set
            {
                this.rPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TOS", IsNullable = false)]
        public TTOS_TOIO[] TOSList
        {
            get
            {
                return this.tOSListField;
            }
            set
            {
                this.tOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SPR", IsNullable = false)]
        public TSPR_SPIO[] SPRList
        {
            get
            {
                return this.sPRListField;
            }
            set
            {
                this.sPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RVE", IsNullable = false)]
        public TRVE_RVXO[] RVEList
        {
            get
            {
                return this.rVEListField;
            }
            set
            {
                this.rVEListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("POB", IsNullable = false)]
        public TPOB_PHRO[] POBList
        {
            get
            {
                return this.pOBListField;
            }
            set
            {
                this.pOBListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZPO", IsNullable = false)]
        public TZPOO[] ZPOList
        {
            get
            {
                return this.zPOListField;
            }
            set
            {
                this.zPOListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PZM", IsNullable = false)]
        public TPZMO[] PZMList
        {
            get
            {
                return this.pZMListField;
            }
            set
            {
                this.pZMListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DCD", IsNullable = false)]
        public TDCD_DCIO[] DCDList
        {
            get
            {
                return this.dCDListField;
            }
            set
            {
                this.dCDListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("USO", IsNullable = false)]
        public TUSOO[] USOList
        {
            get
            {
                return this.uSOListField;
            }
            set
            {
                this.uSOListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SNR", IsNullable = false)]
        public TSNR_SNPO[] SNRList
        {
            get
            {
                return this.sNRListField;
            }
            set
            {
                this.sNRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZUD", IsNullable = false)]
        public TZUD_ZUNO[] ZUDList
        {
            get
            {
                return this.zUDListField;
            }
            set
            {
                this.zUDListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ID")]
        public int ID1
        {
            get
            {
                return this.iD1Field;
            }
            set
            {
                this.iD1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID1Specified
        {
            get
            {
                return this.iD1FieldSpecified;
            }
            set
            {
                this.iD1FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TPOVO
    {

        private string nuField;

        private int koField;

        private System.DateTime acField;

        private TOEX_OEIO[] oEXListField;

        /// <remarks/>
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        public int KO
        {
            get
            {
                return this.koField;
            }
            set
            {
                this.koField = value;
            }
        }

        /// <remarks/>
        public System.DateTime AC
        {
            get
            {
                return this.acField;
            }
            set
            {
                this.acField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OEX", IsNullable = false)]
        public TOEX_OEIO[] OEXList
        {
            get
            {
                return this.oEXListField;
            }
            set
            {
                this.oEXListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TSPI_SPN
    {

        private string tUDHONAField;

        private int hoField;

        /// <remarks/>
        public string TUDHONA
        {
            get
            {
                return this.tUDHONAField;
            }
            set
            {
                this.tUDHONAField = value;
            }
        }

        /// <remarks/>
        public int HO
        {
            get
            {
                return this.hoField;
            }
            set
            {
                this.hoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0." +
        "xsd", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TPOVO pOVField;

        private string corrIDField;

        /// <remarks/>
        public TPOVO POV
        {
            get
            {
                return this.pOVField;
            }
            set
            {
                this.pOVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
