//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.PoskytnutieZoznamuIFOPodlaVyhladavacichKriteriiWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TPOD pODField;

        private string corrIDField;

        /// <remarks/>
        public TPOD POD
        {
            get
            {
                return this.pODField;
            }
            set
            {
                this.pODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TPOD
    {

        private TOEX_OEI oEXField;

        private TUES uESField;

        /// <remarks/>
        public TOEX_OEI OEX
        {
            get
            {
                return this.oEXField;
            }
            set
            {
                this.oEXField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TOEX_OEI
    {

        private string rcField;

        private System.DateTime dnField;

        private bool dnFieldSpecified;

        private int piField;

        private bool piFieldSpecified;

        private string pOHPINAField;

        private string biField;

        private int rnField;

        private bool rnFieldSpecified;

        private TMOS[] mOSListField;

        private TPRI[] pRIListField;

        private TRPR[] rPRListField;

        /// <remarks/>
        public string RC
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DN
        {
            get
            {
                return this.dnField;
            }
            set
            {
                this.dnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DNSpecified
        {
            get
            {
                return this.dnFieldSpecified;
            }
            set
            {
                this.dnFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int PI
        {
            get
            {
                return this.piField;
            }
            set
            {
                this.piField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PISpecified
        {
            get
            {
                return this.piFieldSpecified;
            }
            set
            {
                this.piFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string POHPINA
        {
            get
            {
                return this.pOHPINAField;
            }
            set
            {
                this.pOHPINAField = value;
            }
        }

        /// <remarks/>
        public string BI
        {
            get
            {
                return this.biField;
            }
            set
            {
                this.biField = value;
            }
        }

        /// <remarks/>
        public int RN
        {
            get
            {
                return this.rnField;
            }
            set
            {
                this.rnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RNSpecified
        {
            get
            {
                return this.rnFieldSpecified;
            }
            set
            {
                this.rnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MOS", IsNullable = false)]
        public TMOS[] MOSList
        {
            get
            {
                return this.mOSListField;
            }
            set
            {
                this.mOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PRI", IsNullable = false)]
        public TPRI[] PRIList
        {
            get
            {
                return this.pRIListField;
            }
            set
            {
                this.pRIListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RPR", IsNullable = false)]
        public TRPR[] RPRList
        {
            get
            {
                return this.rPRListField;
            }
            set
            {
                this.rPRListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TMOS
    {

        private string meField;

        /// <remarks/>
        public string ME
        {
            get
            {
                return this.meField;
            }
            set
            {
                this.meField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TREGO
    {

        private int poField;

        private string reField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string RE
        {
            get
            {
                return this.reField;
            }
            set
            {
                this.reField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TPOB_PHRO
    {

        private int tpField;

        private string tbField;

        private System.Nullable<System.DateTime> dpField;

        private System.Nullable<System.DateTime> duField;

        private string noField;

        private System.Nullable<int> scField;

        private string ncField;

        private string nkField;

        private string nuField;

        private System.Nullable<int> stField;

        private string nsField;

        private string mpField;

        private string opField;

        private string ooField;

        private string ccField;

        private string umField;

        private string osField;

        private string siField;

        private string cuField;

        private bool pmField;

        private string pcField;

        private string cbField;

        private string iaField;

        private System.Nullable<int> vdField;

        private bool vdFieldSpecified;

        private System.Nullable<int> diField;

        private bool diFieldSpecified;

        private System.Nullable<int> uiField;

        private bool uiFieldSpecified;

        private System.Nullable<int> ceField;

        private bool ceFieldSpecified;

        private System.Nullable<int> oaField;

        private bool oaFieldSpecified;

        private System.Nullable<int> ueField;

        private bool ueFieldSpecified;

        private string olField;

        private TREGO[] rEGListField;

        private int idField;

        /// <remarks/>
        public int TP
        {
            get
            {
                return this.tpField;
            }
            set
            {
                this.tpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TB
        {
            get
            {
                return this.tbField;
            }
            set
            {
                this.tbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NO
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SC
        {
            get
            {
                return this.scField;
            }
            set
            {
                this.scField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NC
        {
            get
            {
                return this.ncField;
            }
            set
            {
                this.ncField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NS
        {
            get
            {
                return this.nsField;
            }
            set
            {
                this.nsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MP
        {
            get
            {
                return this.mpField;
            }
            set
            {
                this.mpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OP
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OO
        {
            get
            {
                return this.ooField;
            }
            set
            {
                this.ooField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OS
        {
            get
            {
                return this.osField;
            }
            set
            {
                this.osField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CU
        {
            get
            {
                return this.cuField;
            }
            set
            {
                this.cuField = value;
            }
        }

        /// <remarks/>
        public bool PM
        {
            get
            {
                return this.pmField;
            }
            set
            {
                this.pmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PC
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CB
        {
            get
            {
                return this.cbField;
            }
            set
            {
                this.cbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IA
        {
            get
            {
                return this.iaField;
            }
            set
            {
                this.iaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> VD
        {
            get
            {
                return this.vdField;
            }
            set
            {
                this.vdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VDSpecified
        {
            get
            {
                return this.vdFieldSpecified;
            }
            set
            {
                this.vdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DI
        {
            get
            {
                return this.diField;
            }
            set
            {
                this.diField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DISpecified
        {
            get
            {
                return this.diFieldSpecified;
            }
            set
            {
                this.diFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UI
        {
            get
            {
                return this.uiField;
            }
            set
            {
                this.uiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UISpecified
        {
            get
            {
                return this.uiFieldSpecified;
            }
            set
            {
                this.uiFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> CE
        {
            get
            {
                return this.ceField;
            }
            set
            {
                this.ceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CESpecified
        {
            get
            {
                return this.ceFieldSpecified;
            }
            set
            {
                this.ceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> OA
        {
            get
            {
                return this.oaField;
            }
            set
            {
                this.oaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OASpecified
        {
            get
            {
                return this.oaFieldSpecified;
            }
            set
            {
                this.oaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UESpecified
        {
            get
            {
                return this.ueFieldSpecified;
            }
            set
            {
                this.ueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OL
        {
            get
            {
                return this.olField;
            }
            set
            {
                this.olField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("REG", IsNullable = false)]
        public TREGO[] REGList
        {
            get
            {
                return this.rEGListField;
            }
            set
            {
                this.rEGListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TRPRO
    {

        private string rpField;

        /// <remarks/>
        public string RP
        {
            get
            {
                return this.rpField;
            }
            set
            {
                this.rpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TPRIO
    {

        private string prField;

        /// <remarks/>
        public string PR
        {
            get
            {
                return this.prField;
            }
            set
            {
                this.prField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TMOSO
    {

        private string meField;

        /// <remarks/>
        public string ME
        {
            get
            {
                return this.meField;
            }
            set
            {
                this.meField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TOEX_OEIO
    {

        private string dpField;

        private System.Nullable<int> nkField;

        private string idField;

        private string poField;

        private System.Nullable<System.DateTime> dnField;

        private bool dnFieldSpecified;

        private string rcField;

        private System.Nullable<int> piField;

        private bool piFieldSpecified;

        private string pOHPINAField;

        private string biField;

        private System.Nullable<int> rnField;

        private bool rnFieldSpecified;

        private System.Nullable<int> szField;

        private bool szFieldSpecified;

        private string sZVSZNAField;

        private TMOSO[] mOSListField;

        private TPRIO[] pRIListField;

        private TRPRO[] rPRListField;

        private TPOB_PHRO[] pOBListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DN
        {
            get
            {
                return this.dnField;
            }
            set
            {
                this.dnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DNSpecified
        {
            get
            {
                return this.dnFieldSpecified;
            }
            set
            {
                this.dnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RC
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PI
        {
            get
            {
                return this.piField;
            }
            set
            {
                this.piField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PISpecified
        {
            get
            {
                return this.piFieldSpecified;
            }
            set
            {
                this.piFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string POHPINA
        {
            get
            {
                return this.pOHPINAField;
            }
            set
            {
                this.pOHPINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BI
        {
            get
            {
                return this.biField;
            }
            set
            {
                this.biField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> RN
        {
            get
            {
                return this.rnField;
            }
            set
            {
                this.rnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RNSpecified
        {
            get
            {
                return this.rnFieldSpecified;
            }
            set
            {
                this.rnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SZ
        {
            get
            {
                return this.szField;
            }
            set
            {
                this.szField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SZSpecified
        {
            get
            {
                return this.szFieldSpecified;
            }
            set
            {
                this.szFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SZVSZNA
        {
            get
            {
                return this.sZVSZNAField;
            }
            set
            {
                this.sZVSZNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MOS", IsNullable = false)]
        public TMOSO[] MOSList
        {
            get
            {
                return this.mOSListField;
            }
            set
            {
                this.mOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PRI", IsNullable = false)]
        public TPRIO[] PRIList
        {
            get
            {
                return this.pRIListField;
            }
            set
            {
                this.pRIListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RPR", IsNullable = false)]
        public TRPRO[] RPRList
        {
            get
            {
                return this.rPRListField;
            }
            set
            {
                this.rPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("POB", IsNullable = false)]
        public TPOB_PHRO[] POBList
        {
            get
            {
                return this.pOBListField;
            }
            set
            {
                this.pOBListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TPOVO
    {

        private string nuField;

        private int koField;

        private System.DateTime acField;

        private TOEX_OEIO[] oEXListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        public int KO
        {
            get
            {
                return this.koField;
            }
            set
            {
                this.koField = value;
            }
        }

        /// <remarks/>
        public System.DateTime AC
        {
            get
            {
                return this.acField;
            }
            set
            {
                this.acField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OEX", IsNullable = false)]
        public TOEX_OEIO[] OEXList
        {
            get
            {
                return this.oEXListField;
            }
            set
            {
                this.oEXListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TRPR
    {

        private string rpField;

        /// <remarks/>
        public string RP
        {
            get
            {
                return this.rpField;
            }
            set
            {
                this.rpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public partial class TPRI
    {

        private string prField;

        /// <remarks/>
        public string PR
        {
            get
            {
                return this.prField;
            }
            set
            {
                this.prField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieZoznamuIFOPodlaVyhladav" +
        "acichKriteriiWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TPOVO pOVField;

        private string corrIDField;

        /// <remarks/>
        public TPOVO POV
        {
            get
            {
                return this.pOVField;
            }
            set
            {
                this.pOVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
