//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.PotvrdzovaniePrijatiaZmienWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TPPZ_ZZV pPZField;

        private TUES uESField;

        private TVDO vDOField;

        private string corrIDField;

        /// <remarks/>
        public TPPZ_ZZV PPZ
        {
            get
            {
                return this.pPZField;
            }
            set
            {
                this.pPZField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }

        /// <remarks/>
        public TVDO VDO
        {
            get
            {
                return this.vDOField;
            }
            set
            {
                this.vDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    public partial class TPPZ_ZZV
    {

        private long ipField;

        /// <remarks/>
        public long IP
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    public partial class TVSPO
    {

        private int kiField;

        private string poField;

        /// <remarks/>
        public int KI
        {
            get
            {
                return this.kiField;
            }
            set
            {
                this.kiField = value;
            }
        }

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    public partial class TVDO
    {

        private string idField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/PrijatieZmienWS-v1.0", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TVSPO vSPField;

        private string corrIDField;

        /// <remarks/>
        public TVSPO VSP
        {
            get
            {
                return this.vSPField;
            }
            set
            {
                this.vSPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
