//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.ZapisNovychOsobWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TOEX_OEI[] oEXListField;

        private TUES uESField;

        private string corrIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OEX", IsNullable = false)]
        public TOEX_OEI[] OEXList
        {
            get
            {
                return this.oEXListField;
            }
            set
            {
                this.oEXListField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TOEX_OEI
    {

        private int paField;

        private int tvField;

        private string tVKTVNAField;

        private string rcField;

        private System.DateTime dnField;

        private bool dnFieldSpecified;

        private int rnField;

        private bool rnFieldSpecified;

        private string mrField;

        private int ucField;

        private bool ucFieldSpecified;

        private string uCEUCNAField;

        private int poField;

        private string pOHPONAField;

        private int snField;

        private bool snFieldSpecified;

        private string sTASNNAField;

        private int pgField;

        private bool pgFieldSpecified;

        private string pRAPGNAField;

        private int rsField;

        private bool rsFieldSpecified;

        private string rSTRSNAField;

        private int niField;

        private bool niFieldSpecified;

        private string nARNINAField;

        private bool zrField;

        private int szField;

        private string sZVSZNAField;

        private string icField;

        private string onField;

        private System.DateTime d2Field;

        private bool d2FieldSpecified;

        private int u2Field;

        private bool u2FieldSpecified;

        private string uCEU2NAField;

        private string m2Field;

        private int s2Field;

        private bool s2FieldSpecified;

        private string sTAS2NAField;

        private int peField;

        private bool peFieldSpecified;

        private string pRAPENAField;

        private string ouField;

        private TMOS[] mOSListField;

        private TPRI[] pRIListField;

        private TRPR[] rPRListField;

        private TTOS_TOI[] tOSListField;

        private TSPR_SPI[] sPRListField;

        private TPOB_PHR[] pOBListField;

        private TPZR pZRField;

        /// <remarks/>
        public int PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        public int TV
        {
            get
            {
                return this.tvField;
            }
            set
            {
                this.tvField = value;
            }
        }

        /// <remarks/>
        public string TVKTVNA
        {
            get
            {
                return this.tVKTVNAField;
            }
            set
            {
                this.tVKTVNAField = value;
            }
        }

        /// <remarks/>
        public string RC
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DN
        {
            get
            {
                return this.dnField;
            }
            set
            {
                this.dnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DNSpecified
        {
            get
            {
                return this.dnFieldSpecified;
            }
            set
            {
                this.dnFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int RN
        {
            get
            {
                return this.rnField;
            }
            set
            {
                this.rnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RNSpecified
        {
            get
            {
                return this.rnFieldSpecified;
            }
            set
            {
                this.rnFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string MR
        {
            get
            {
                return this.mrField;
            }
            set
            {
                this.mrField = value;
            }
        }

        /// <remarks/>
        public int UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UCSpecified
        {
            get
            {
                return this.ucFieldSpecified;
            }
            set
            {
                this.ucFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string POHPONA
        {
            get
            {
                return this.pOHPONAField;
            }
            set
            {
                this.pOHPONAField = value;
            }
        }

        /// <remarks/>
        public int SN
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNSpecified
        {
            get
            {
                return this.snFieldSpecified;
            }
            set
            {
                this.snFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string STASNNA
        {
            get
            {
                return this.sTASNNAField;
            }
            set
            {
                this.sTASNNAField = value;
            }
        }

        /// <remarks/>
        public int PG
        {
            get
            {
                return this.pgField;
            }
            set
            {
                this.pgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PGSpecified
        {
            get
            {
                return this.pgFieldSpecified;
            }
            set
            {
                this.pgFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PRAPGNA
        {
            get
            {
                return this.pRAPGNAField;
            }
            set
            {
                this.pRAPGNAField = value;
            }
        }

        /// <remarks/>
        public int RS
        {
            get
            {
                return this.rsField;
            }
            set
            {
                this.rsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSSpecified
        {
            get
            {
                return this.rsFieldSpecified;
            }
            set
            {
                this.rsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RSTRSNA
        {
            get
            {
                return this.rSTRSNAField;
            }
            set
            {
                this.rSTRSNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement()]
        public int NI
        {
            get
            {
                return this.niField;
            }
            set
            {
                this.niField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NISpecified
        {
            get
            {
                return this.niFieldSpecified;
            }
            set
            {
                this.niFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NARNINA
        {
            get
            {
                return this.nARNINAField;
            }
            set
            {
                this.nARNINAField = value;
            }
        }

        /// <remarks/>
        public bool ZR
        {
            get
            {
                return this.zrField;
            }
            set
            {
                this.zrField = value;
            }
        }

        /// <remarks/>
        public int SZ
        {
            get
            {
                return this.szField;
            }
            set
            {
                this.szField = value;
            }
        }

        /// <remarks/>
        public string SZVSZNA
        {
            get
            {
                return this.sZVSZNAField;
            }
            set
            {
                this.sZVSZNAField = value;
            }
        }

        /// <remarks/>
        public string IC
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }

        /// <remarks/>
        public string ON
        {
            get
            {
                return this.onField;
            }
            set
            {
                this.onField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime D2
        {
            get
            {
                return this.d2Field;
            }
            set
            {
                this.d2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D2Specified
        {
            get
            {
                return this.d2FieldSpecified;
            }
            set
            {
                this.d2FieldSpecified = value;
            }
        }

        /// <remarks/>
        public int U2
        {
            get
            {
                return this.u2Field;
            }
            set
            {
                this.u2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool U2Specified
        {
            get
            {
                return this.u2FieldSpecified;
            }
            set
            {
                this.u2FieldSpecified = value;
            }
        }

        /// <remarks/>
        public string UCEU2NA
        {
            get
            {
                return this.uCEU2NAField;
            }
            set
            {
                this.uCEU2NAField = value;
            }
        }

        /// <remarks/>
        public string M2
        {
            get
            {
                return this.m2Field;
            }
            set
            {
                this.m2Field = value;
            }
        }

        /// <remarks/>
        public int S2
        {
            get
            {
                return this.s2Field;
            }
            set
            {
                this.s2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool S2Specified
        {
            get
            {
                return this.s2FieldSpecified;
            }
            set
            {
                this.s2FieldSpecified = value;
            }
        }

        /// <remarks/>
        public string STAS2NA
        {
            get
            {
                return this.sTAS2NAField;
            }
            set
            {
                this.sTAS2NAField = value;
            }
        }

        /// <remarks/>
        public int PE
        {
            get
            {
                return this.peField;
            }
            set
            {
                this.peField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PESpecified
        {
            get
            {
                return this.peFieldSpecified;
            }
            set
            {
                this.peFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PRAPENA
        {
            get
            {
                return this.pRAPENAField;
            }
            set
            {
                this.pRAPENAField = value;
            }
        }

        /// <remarks/>
        public string OU
        {
            get
            {
                return this.ouField;
            }
            set
            {
                this.ouField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MOS", IsNullable = false)]
        public TMOS[] MOSList
        {
            get
            {
                return this.mOSListField;
            }
            set
            {
                this.mOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PRI", IsNullable = false)]
        public TPRI[] PRIList
        {
            get
            {
                return this.pRIListField;
            }
            set
            {
                this.pRIListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RPR", IsNullable = false)]
        public TRPR[] RPRList
        {
            get
            {
                return this.rPRListField;
            }
            set
            {
                this.rPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TOS", IsNullable = false)]
        public TTOS_TOI[] TOSList
        {
            get
            {
                return this.tOSListField;
            }
            set
            {
                this.tOSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SPR", IsNullable = false)]
        public TSPR_SPI[] SPRList
        {
            get
            {
                return this.sPRListField;
            }
            set
            {
                this.sPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("POB", IsNullable = false)]
        public TPOB_PHR[] POBList
        {
            get
            {
                return this.pOBListField;
            }
            set
            {
                this.pOBListField = value;
            }
        }

        /// <remarks/>
        public TPZR PZR
        {
            get
            {
                return this.pZRField;
            }
            set
            {
                this.pZRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TMOS
    {

        private string meField;

        private int poField;

        /// <remarks/>
        public string ME
        {
            get
            {
                return this.meField;
            }
            set
            {
                this.meField = value;
            }
        }

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TOEXO
    {

        private int paField;

        private string idField;

        private int nkField;

        private string drField;

        /// <remarks/>
        public int PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public int NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        public string DR
        {
            get
            {
                return this.drField;
            }
            set
            {
                this.drField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TVSPO
    {

        private int kiField;

        private string poField;

        private TOEXO[] oEXListField;

        /// <remarks/>
        public int KI
        {
            get
            {
                return this.kiField;
            }
            set
            {
                this.kiField = value;
            }
        }

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OEX", IsNullable = false)]
        public TOEXO[] OEXList
        {
            get
            {
                return this.oEXListField;
            }
            set
            {
                this.oEXListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TPZR
    {

        private System.DateTime dpField;

        private bool dpFieldSpecified;

        private string crField;

        private System.DateTime dvField;

        private bool dvFieldSpecified;

        private string okField;

        private int siField;

        private bool siFieldSpecified;

        private string sUDSINAField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPSpecified
        {
            get
            {
                return this.dpFieldSpecified;
            }
            set
            {
                this.dpFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CR
        {
            get
            {
                return this.crField;
            }
            set
            {
                this.crField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DV
        {
            get
            {
                return this.dvField;
            }
            set
            {
                this.dvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DVSpecified
        {
            get
            {
                return this.dvFieldSpecified;
            }
            set
            {
                this.dvFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string OK
        {
            get
            {
                return this.okField;
            }
            set
            {
                this.okField = value;
            }
        }

        /// <remarks/>
        public int SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SISpecified
        {
            get
            {
                return this.siFieldSpecified;
            }
            set
            {
                this.siFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string SUDSINA
        {
            get
            {
                return this.sUDSINAField;
            }
            set
            {
                this.sUDSINAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TREG
    {

        private int poField;

        private string reField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string RE
        {
            get
            {
                return this.reField;
            }
            set
            {
                this.reField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TPOB_PHR
    {

        private int tpField;

        private string tbField;

        private System.DateTime dpField;

        private bool dpFieldSpecified;

        private System.DateTime duField;

        private bool duFieldSpecified;

        private string ncField;

        private string noField;

        private string nkField;

        private string nuField;

        private int ocField;

        private bool ocFieldSpecified;

        private string zoField;

        private int scField;

        private bool scFieldSpecified;

        private string pcField;

        private string mpField;

        private string ccField;

        private string ooField;

        private string opField;

        private string osField;

        private string umField;

        private string siField;

        private string cuField;

        private int stField;

        private bool stFieldSpecified;

        private string nsField;

        private bool pmField;

        private string iaField;

        private int uiField;

        private bool uiFieldSpecified;

        private int ueField;

        private bool ueFieldSpecified;

        private int uaField;

        private bool uaFieldSpecified;

        private int urField;

        private bool urFieldSpecified;

        private string cbField;

        private int diField;

        private bool diFieldSpecified;

        private int vdField;

        private bool vdFieldSpecified;

        private TREG[] rEGListField;

        /// <remarks/>
        public int TP
        {
            get
            {
                return this.tpField;
            }
            set
            {
                this.tpField = value;
            }
        }

        /// <remarks/>
        public string TB
        {
            get
            {
                return this.tbField;
            }
            set
            {
                this.tbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPSpecified
        {
            get
            {
                return this.dpFieldSpecified;
            }
            set
            {
                this.dpFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DUSpecified
        {
            get
            {
                return this.duFieldSpecified;
            }
            set
            {
                this.duFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NC
        {
            get
            {
                return this.ncField;
            }
            set
            {
                this.ncField = value;
            }
        }

        /// <remarks/>
        public string NO
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        /// <remarks/>
        public string NK
        {
            get
            {
                return this.nkField;
            }
            set
            {
                this.nkField = value;
            }
        }

        /// <remarks/>
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        public int OC
        {
            get
            {
                return this.ocField;
            }
            set
            {
                this.ocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OCSpecified
        {
            get
            {
                return this.ocFieldSpecified;
            }
            set
            {
                this.ocFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ZO
        {
            get
            {
                return this.zoField;
            }
            set
            {
                this.zoField = value;
            }
        }

        /// <remarks/>
        public int SC
        {
            get
            {
                return this.scField;
            }
            set
            {
                this.scField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SCSpecified
        {
            get
            {
                return this.scFieldSpecified;
            }
            set
            {
                this.scFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PC
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        public string MP
        {
            get
            {
                return this.mpField;
            }
            set
            {
                this.mpField = value;
            }
        }

        /// <remarks/>
        public string CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        public string OO
        {
            get
            {
                return this.ooField;
            }
            set
            {
                this.ooField = value;
            }
        }

        /// <remarks/>
        public string OP
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }

        /// <remarks/>
        public string OS
        {
            get
            {
                return this.osField;
            }
            set
            {
                this.osField = value;
            }
        }

        /// <remarks/>
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        public string SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        public string CU
        {
            get
            {
                return this.cuField;
            }
            set
            {
                this.cuField = value;
            }
        }

        /// <remarks/>
        public int ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STSpecified
        {
            get
            {
                return this.stFieldSpecified;
            }
            set
            {
                this.stFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NS
        {
            get
            {
                return this.nsField;
            }
            set
            {
                this.nsField = value;
            }
        }

        /// <remarks/>
        public bool PM
        {
            get
            {
                return this.pmField;
            }
            set
            {
                this.pmField = value;
            }
        }

        /// <remarks/>
        public string IA
        {
            get
            {
                return this.iaField;
            }
            set
            {
                this.iaField = value;
            }
        }

        /// <remarks/>
        public int UI
        {
            get
            {
                return this.uiField;
            }
            set
            {
                this.uiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UISpecified
        {
            get
            {
                return this.uiFieldSpecified;
            }
            set
            {
                this.uiFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UESpecified
        {
            get
            {
                return this.ueFieldSpecified;
            }
            set
            {
                this.ueFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int UA
        {
            get
            {
                return this.uaField;
            }
            set
            {
                this.uaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UASpecified
        {
            get
            {
                return this.uaFieldSpecified;
            }
            set
            {
                this.uaFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int UR
        {
            get
            {
                return this.urField;
            }
            set
            {
                this.urField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool URSpecified
        {
            get
            {
                return this.urFieldSpecified;
            }
            set
            {
                this.urFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CB
        {
            get
            {
                return this.cbField;
            }
            set
            {
                this.cbField = value;
            }
        }

        /// <remarks/>
        public int DI
        {
            get
            {
                return this.diField;
            }
            set
            {
                this.diField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DISpecified
        {
            get
            {
                return this.diFieldSpecified;
            }
            set
            {
                this.diFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int VD
        {
            get
            {
                return this.vdField;
            }
            set
            {
                this.vdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VDSpecified
        {
            get
            {
                return this.vdFieldSpecified;
            }
            set
            {
                this.vdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("REG", IsNullable = false)]
        public TREG[] REGList
        {
            get
            {
                return this.rEGListField;
            }
            set
            {
                this.rEGListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TSPR_SPI
    {

        private int stField;

        private string sTASTNAField;

        /// <remarks/>
        public int ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        public string STASTNA
        {
            get
            {
                return this.sTASTNAField;
            }
            set
            {
                this.sTASTNAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TTOS_TOI
    {

        private int tiField;

        private string tITTINAField;

        private int ttField;

        private string tTITTNAField;

        /// <remarks/>
        public int TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }

        /// <remarks/>
        public string TITTINA
        {
            get
            {
                return this.tITTINAField;
            }
            set
            {
                this.tITTINAField = value;
            }
        }

        /// <remarks/>
        public int TT
        {
            get
            {
                return this.ttField;
            }
            set
            {
                this.ttField = value;
            }
        }

        /// <remarks/>
        public string TTITTNA
        {
            get
            {
                return this.tTITTNAField;
            }
            set
            {
                this.tTITTNAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TRPR
    {

        private int poField;

        private string rpField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string RP
        {
            get
            {
                return this.rpField;
            }
            set
            {
                this.rpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public partial class TPRI
    {

        private int poField;

        private string prField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string PR
        {
            get
            {
                return this.prField;
            }
            set
            {
                this.prField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisNovychOsobWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TVSPO vSPField;

        private string corrIDField;

        /// <remarks/>
        public TVSPO VSP
        {
            get
            {
                return this.vSPField;
            }
            set
            {
                this.vSPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
