//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.ZapisUpravyMenaWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TOSO oSOField;

        private TUES uESField;

        private string corrIDField;

        /// <remarks/>
        public TOSO OSO
        {
            get
            {
                return this.oSOField;
            }
            set
            {
                this.oSOField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    public partial class TOSO
    {

        private string idField;

        private long zzField;

        private bool zzFieldSpecified;

        private TMOS_ZIE[] mOSListField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public long ZZ
        {
            get
            {
                return this.zzField;
            }
            set
            {
                this.zzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZZSpecified
        {
            get
            {
                return this.zzFieldSpecified;
            }
            set
            {
                this.zzFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MOS", IsNullable = false)]
        public TMOS_ZIE[] MOSList
        {
            get
            {
                return this.mOSListField;
            }
            set
            {
                this.mOSListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    public partial class TMOS_ZIE
    {

        private bool opField;

        private bool vyField;

        private System.DateTime dzField;

        private bool dzFieldSpecified;

        private int poField;

        private string phField;

        private string nhField;

        private int idField;

        private bool idFieldSpecified;

        /// <remarks/>
        public bool OP
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }

        /// <remarks/>
        public bool VY
        {
            get
            {
                return this.vyField;
            }
            set
            {
                this.vyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DZSpecified
        {
            get
            {
                return this.dzFieldSpecified;
            }
            set
            {
                this.dzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string PH
        {
            get
            {
                return this.phField;
            }
            set
            {
                this.phField = value;
            }
        }

        /// <remarks/>
        public string NH
        {
            get
            {
                return this.nhField;
            }
            set
            {
                this.nhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    public partial class TVSPO
    {

        private int kiField;

        private string poField;

        /// <remarks/>
        public int KI
        {
            get
            {
                return this.kiField;
            }
            set
            {
                this.kiField = value;
            }
        }

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Zapis/Ext/ZapisUpravyMenaWS-v1.0.xsd", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TVSPO vSPField;

        private string corrIDField;

        /// <remarks/>
        public TVSPO VSP
        {
            get
            {
                return this.vSPField;
            }
            set
            {
                this.vSPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
