//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Ditec.RIS.RFO.Dol.ZoznamIFOSoZmenenymiReferencnymiUdajmiWS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvIn", Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0", IsNullable = false)]
    public partial class TransEnvTypeIn : TransEnvelopeType
    {

        private TPOD pODField;

        private string corrIDField;

        /// <remarks/>
        public TPOD POD
        {
            get
            {
                return this.pODField;
            }
            set
            {
                this.pODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TPOD
    {

        private bool udField;

        private TVDO vDOField;

        private TUES uESField;

        /// <remarks/>
        public bool UD
        {
            get
            {
                return this.udField;
            }
            set
            {
                this.udField = value;
            }
        }

        /// <remarks/>
        public TVDO VDO
        {
            get
            {
                return this.vDOField;
            }
            set
            {
                this.vDOField = value;
            }
        }

        /// <remarks/>
        public TUES UES
        {
            get
            {
                return this.uESField;
            }
            set
            {
                this.uESField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TVDO
    {

        private string idField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZUD_ZUNO
    {

        private int zoField;

        private string zOBZONAField;

        /// <remarks/>
        public int ZO
        {
            get
            {
                return this.zoField;
            }
            set
            {
                this.zoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ZOBZONA
        {
            get
            {
                return this.zOBZONAField;
            }
            set
            {
                this.zOBZONAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZDC_ZDDO
    {

        private int ddField;

        private string dDCDDNAField;

        private string ccField;

        private System.Nullable<bool> duField;

        private int idField;

        /// <remarks/>
        public int DD
        {
            get
            {
                return this.ddField;
            }
            set
            {
                this.ddField = value;
            }
        }

        /// <remarks/>
        public string DDCDDNA
        {
            get
            {
                return this.dDCDDNAField;
            }
            set
            {
                this.dDCDDNAField = value;
            }
        }

        /// <remarks/>
        public string CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZREO
    {

        private int poField;

        private string reField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string RE
        {
            get
            {
                return this.reField;
            }
            set
            {
                this.reField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZPB_ZPNO
    {

        private int piField;

        private int tpField;

        private string tPOTPNAField;

        private System.Nullable<System.DateTime> dpField;

        private System.Nullable<System.DateTime> dkField;

        private System.Nullable<bool> pmField;

        private System.Nullable<int> siField;

        private string sTASINAField;

        private System.Nullable<int> ucField;

        private string uCEUCNAField;

        private System.Nullable<int> scField;

        private System.Nullable<int> ocField;

        private string zoField;

        private System.Nullable<int> ueField;

        private string uCEUENAField;

        private System.Nullable<int> ulField;

        private string onField;

        private System.Nullable<int> uiField;

        private string uLIUINAField;

        private string cbField;

        private string opField;

        private string ooField;

        private string coField;

        private string umField;

        private string oiField;

        private string ssField;

        private string mpField;

        private string pcField;

        private string cyField;

        private System.Nullable<int> diField;

        private bool diFieldSpecified;

        private System.Nullable<int> vdField;

        private bool vdFieldSpecified;

        private string iaField;

        private string olField;

        private TZREO[] zREListField;

        private int idField;

        /// <remarks/>
        public int PI
        {
            get
            {
                return this.piField;
            }
            set
            {
                this.piField = value;
            }
        }

        /// <remarks/>
        public int TP
        {
            get
            {
                return this.tpField;
            }
            set
            {
                this.tpField = value;
            }
        }

        /// <remarks/>
        public string TPOTPNA
        {
            get
            {
                return this.tPOTPNAField;
            }
            set
            {
                this.tPOTPNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> PM
        {
            get
            {
                return this.pmField;
            }
            set
            {
                this.pmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string STASINA
        {
            get
            {
                return this.sTASINAField;
            }
            set
            {
                this.sTASINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SC
        {
            get
            {
                return this.scField;
            }
            set
            {
                this.scField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> OC
        {
            get
            {
                return this.ocField;
            }
            set
            {
                this.ocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ZO
        {
            get
            {
                return this.zoField;
            }
            set
            {
                this.zoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUENA
        {
            get
            {
                return this.uCEUENAField;
            }
            set
            {
                this.uCEUENAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UL
        {
            get
            {
                return this.ulField;
            }
            set
            {
                this.ulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ON
        {
            get
            {
                return this.onField;
            }
            set
            {
                this.onField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UI
        {
            get
            {
                return this.uiField;
            }
            set
            {
                this.uiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ULIUINA
        {
            get
            {
                return this.uLIUINAField;
            }
            set
            {
                this.uLIUINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CB
        {
            get
            {
                return this.cbField;
            }
            set
            {
                this.cbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OP
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OO
        {
            get
            {
                return this.ooField;
            }
            set
            {
                this.ooField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CO
        {
            get
            {
                return this.coField;
            }
            set
            {
                this.coField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OI
        {
            get
            {
                return this.oiField;
            }
            set
            {
                this.oiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SS
        {
            get
            {
                return this.ssField;
            }
            set
            {
                this.ssField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MP
        {
            get
            {
                return this.mpField;
            }
            set
            {
                this.mpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PC
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CY
        {
            get
            {
                return this.cyField;
            }
            set
            {
                this.cyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DI
        {
            get
            {
                return this.diField;
            }
            set
            {
                this.diField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DISpecified
        {
            get
            {
                return this.diFieldSpecified;
            }
            set
            {
                this.diFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> VD
        {
            get
            {
                return this.vdField;
            }
            set
            {
                this.vdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VDSpecified
        {
            get
            {
                return this.vdFieldSpecified;
            }
            set
            {
                this.vdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IA
        {
            get
            {
                return this.iaField;
            }
            set
            {
                this.iaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OL
        {
            get
            {
                return this.olField;
            }
            set
            {
                this.olField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZRE", IsNullable = false)]
        public TZREO[] ZREList
        {
            get
            {
                return this.zREListField;
            }
            set
            {
                this.zREListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZZP_ZZOO
    {

        private System.Nullable<System.DateTime> dzField;

        private System.Nullable<System.DateTime> dkField;

        private string poField;

        private System.Nullable<int> ucField;

        private string uCEUCNAField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZUSO
    {

        private System.Nullable<System.DateTime> dpField;

        private bool udField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        public bool UD
        {
            get
            {
                return this.udField;
            }
            set
            {
                this.udField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZHS_ZHPO
    {

        private int saField;

        private string sNPSANAField;

        private System.Nullable<System.DateTime> dzField;

        private System.Nullable<System.DateTime> dkField;

        private string poField;

        private int idField;

        /// <remarks/>
        public int SA
        {
            get
            {
                return this.saField;
            }
            set
            {
                this.saField = value;
            }
        }

        /// <remarks/>
        public string SNPSANA
        {
            get
            {
                return this.sNPSANAField;
            }
            set
            {
                this.sNPSANAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZRV_ZRZO
    {

        private string idField;

        private int trField;

        private string tRZTRNAField;

        private System.Nullable<System.DateTime> dvField;

        private string mvField;

        private System.Nullable<int> ucField;

        private string uCEUCNAField;

        private int toField;

        private string tRRTONAField;

        private int tlField;

        private string tRRTLNAField;

        private string smField;

        private System.Nullable<int> paField;

        private bool paFieldSpecified;

        private int iD1Field;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public int TR
        {
            get
            {
                return this.trField;
            }
            set
            {
                this.trField = value;
            }
        }

        /// <remarks/>
        public string TRZTRNA
        {
            get
            {
                return this.tRZTRNAField;
            }
            set
            {
                this.tRZTRNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DV
        {
            get
            {
                return this.dvField;
            }
            set
            {
                this.dvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MV
        {
            get
            {
                return this.mvField;
            }
            set
            {
                this.mvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        public int TO
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        public string TRRTONA
        {
            get
            {
                return this.tRRTONAField;
            }
            set
            {
                this.tRRTONAField = value;
            }
        }

        /// <remarks/>
        public int TL
        {
            get
            {
                return this.tlField;
            }
            set
            {
                this.tlField = value;
            }
        }

        /// <remarks/>
        public string TRRTLNA
        {
            get
            {
                return this.tRRTLNAField;
            }
            set
            {
                this.tRRTLNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SM
        {
            get
            {
                return this.smField;
            }
            set
            {
                this.smField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PASpecified
        {
            get
            {
                return this.paFieldSpecified;
            }
            set
            {
                this.paFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ID")]
        public int ID1
        {
            get
            {
                return this.iD1Field;
            }
            set
            {
                this.iD1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZSP_ZSRO
    {

        private int siField;

        private string sTASINAField;

        private int idField;

        /// <remarks/>
        public int SI
        {
            get
            {
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        /// <remarks/>
        public string STASINA
        {
            get
            {
                return this.sTASINAField;
            }
            set
            {
                this.sTASINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZTI_ZTNO
    {

        private int tiField;

        private string tITTINAField;

        private int ttField;

        private string tTITTNAField;

        private System.Nullable<System.DateTime> frField;

        private int idField;

        /// <remarks/>
        public int TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }

        /// <remarks/>
        public string TITTINA
        {
            get
            {
                return this.tITTINAField;
            }
            set
            {
                this.tITTINAField = value;
            }
        }

        /// <remarks/>
        public int TT
        {
            get
            {
                return this.ttField;
            }
            set
            {
                this.ttField = value;
            }
        }

        /// <remarks/>
        public string TTITTNA
        {
            get
            {
                return this.tTITTNAField;
            }
            set
            {
                this.tTITTNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> FR
        {
            get
            {
                return this.frField;
            }
            set
            {
                this.frField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZRPO
    {

        private int poField;

        private string rpField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RP
        {
            get
            {
                return this.rpField;
            }
            set
            {
                this.rpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZPRO
    {

        private int poField;

        private string prField;

        private int idField;

        /// <remarks/>
        public int PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PR
        {
            get
            {
                return this.prField;
            }
            set
            {
                this.prField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZMEO
    {

        private string meField;

        private int paField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ME
        {
            get
            {
                return this.meField;
            }
            set
            {
                this.meField = value;
            }
        }

        /// <remarks/>
        public int PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TZZV_ZZDO
    {

        private long zzField;

        private string idField;

        private string niField;

        private System.Nullable<int> szField;

        private string sZVSZNAField;

        private System.Nullable<System.DateTime> duField;

        private System.Nullable<System.DateTime> dnField;

        private string rcField;

        private System.Nullable<int> rsField;

        private string rSTRSNAField;

        private System.Nullable<int> poField;

        private string pOHPONAField;

        private System.Nullable<int> ndField;

        private string nARNDNAField;

        private string mnField;

        private System.Nullable<int> ucField;

        private string uCEUCNAField;

        private string onField;

        private System.Nullable<int> ueField;

        private string uCEUENAField;

        private System.Nullable<int> snField;

        private string sTASNNAField;

        private string muField;

        private System.Nullable<int> ulField;

        private string uCEULNAField;

        private string ouField;

        private System.Nullable<int> uoField;

        private string uCEUONAField;

        private System.Nullable<int> suField;

        private string sTASUNAField;

        private System.Nullable<System.DateTime> dkField;

        private string dtField;

        private System.Nullable<System.DateTime> dpField;

        private string icField;

        private System.Nullable<int> paField;

        private string rmField;

        private System.Nullable<int> pgField;

        private string umField;

        private string biField;

        private System.Nullable<long> ipField;

        private System.Nullable<int> tvField;

        private string tVKTVNAField;

        private System.Nullable<int> rnField;

        private bool rnFieldSpecified;

        private System.Nullable<System.DateTime> daField;

        private System.Nullable<System.DateTime> dzField;

        private System.Nullable<int> spField;

        private string sPZSPNAField;

        private string nuField;

        private System.Nullable<int> koField;

        private bool koFieldSpecified;

        private TZMEO[] zMEListField;

        private TZPRO[] zPRListField;

        private TZRPO[] zRPListField;

        private TZTI_ZTNO[] zTIListField;

        private TZSP_ZSRO[] zSPListField;

        private TZRV_ZRZO[] zRVListField;

        private TZHS_ZHPO[] zHSListField;

        private TZUSO[] zUSListField;

        private TZZP_ZZOO[] zZPListField;

        private TZPB_ZPNO[] zPBListField;

        private TZDC_ZDDO[] zDCListField;

        private TZUD_ZUNO[] zUDListField;

        /// <remarks/>
        public long ZZ
        {
            get
            {
                return this.zzField;
            }
            set
            {
                this.zzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NI
        {
            get
            {
                return this.niField;
            }
            set
            {
                this.niField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SZ
        {
            get
            {
                return this.szField;
            }
            set
            {
                this.szField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SZVSZNA
        {
            get
            {
                return this.sZVSZNAField;
            }
            set
            {
                this.sZVSZNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DU
        {
            get
            {
                return this.duField;
            }
            set
            {
                this.duField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DN
        {
            get
            {
                return this.dnField;
            }
            set
            {
                this.dnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RC
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> RS
        {
            get
            {
                return this.rsField;
            }
            set
            {
                this.rsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RSTRSNA
        {
            get
            {
                return this.rSTRSNAField;
            }
            set
            {
                this.rSTRSNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string POHPONA
        {
            get
            {
                return this.pOHPONAField;
            }
            set
            {
                this.pOHPONAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ND
        {
            get
            {
                return this.ndField;
            }
            set
            {
                this.ndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NARNDNA
        {
            get
            {
                return this.nARNDNAField;
            }
            set
            {
                this.nARNDNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MN
        {
            get
            {
                return this.mnField;
            }
            set
            {
                this.mnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UC
        {
            get
            {
                return this.ucField;
            }
            set
            {
                this.ucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUCNA
        {
            get
            {
                return this.uCEUCNAField;
            }
            set
            {
                this.uCEUCNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ON
        {
            get
            {
                return this.onField;
            }
            set
            {
                this.onField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UE
        {
            get
            {
                return this.ueField;
            }
            set
            {
                this.ueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUENA
        {
            get
            {
                return this.uCEUENAField;
            }
            set
            {
                this.uCEUENAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SN
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string STASNNA
        {
            get
            {
                return this.sTASNNAField;
            }
            set
            {
                this.sTASNNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MU
        {
            get
            {
                return this.muField;
            }
            set
            {
                this.muField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UL
        {
            get
            {
                return this.ulField;
            }
            set
            {
                this.ulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEULNA
        {
            get
            {
                return this.uCEULNAField;
            }
            set
            {
                this.uCEULNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OU
        {
            get
            {
                return this.ouField;
            }
            set
            {
                this.ouField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UO
        {
            get
            {
                return this.uoField;
            }
            set
            {
                this.uoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UCEUONA
        {
            get
            {
                return this.uCEUONAField;
            }
            set
            {
                this.uCEUONAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SU
        {
            get
            {
                return this.suField;
            }
            set
            {
                this.suField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string STASUNA
        {
            get
            {
                return this.sTASUNAField;
            }
            set
            {
                this.sTASUNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DK
        {
            get
            {
                return this.dkField;
            }
            set
            {
                this.dkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DT
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DP
        {
            get
            {
                return this.dpField;
            }
            set
            {
                this.dpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IC
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PA
        {
            get
            {
                return this.paField;
            }
            set
            {
                this.paField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RM
        {
            get
            {
                return this.rmField;
            }
            set
            {
                this.rmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PG
        {
            get
            {
                return this.pgField;
            }
            set
            {
                this.pgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UM
        {
            get
            {
                return this.umField;
            }
            set
            {
                this.umField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BI
        {
            get
            {
                return this.biField;
            }
            set
            {
                this.biField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<long> IP
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> TV
        {
            get
            {
                return this.tvField;
            }
            set
            {
                this.tvField = value;
            }
        }

        /// <remarks/>
        public string TVKTVNA
        {
            get
            {
                return this.tVKTVNAField;
            }
            set
            {
                this.tVKTVNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> RN
        {
            get
            {
                return this.rnField;
            }
            set
            {
                this.rnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RNSpecified
        {
            get
            {
                return this.rnFieldSpecified;
            }
            set
            {
                this.rnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DA
        {
            get
            {
                return this.daField;
            }
            set
            {
                this.daField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> DZ
        {
            get
            {
                return this.dzField;
            }
            set
            {
                this.dzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SP
        {
            get
            {
                return this.spField;
            }
            set
            {
                this.spField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SPZSPNA
        {
            get
            {
                return this.sPZSPNAField;
            }
            set
            {
                this.sPZSPNAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> KO
        {
            get
            {
                return this.koField;
            }
            set
            {
                this.koField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KOSpecified
        {
            get
            {
                return this.koFieldSpecified;
            }
            set
            {
                this.koFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZME", IsNullable = false)]
        public TZMEO[] ZMEList
        {
            get
            {
                return this.zMEListField;
            }
            set
            {
                this.zMEListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZPR", IsNullable = false)]
        public TZPRO[] ZPRList
        {
            get
            {
                return this.zPRListField;
            }
            set
            {
                this.zPRListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZRP", IsNullable = false)]
        public TZRPO[] ZRPList
        {
            get
            {
                return this.zRPListField;
            }
            set
            {
                this.zRPListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZTI", IsNullable = false)]
        public TZTI_ZTNO[] ZTIList
        {
            get
            {
                return this.zTIListField;
            }
            set
            {
                this.zTIListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZSP", IsNullable = false)]
        public TZSP_ZSRO[] ZSPList
        {
            get
            {
                return this.zSPListField;
            }
            set
            {
                this.zSPListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZRV", IsNullable = false)]
        public TZRV_ZRZO[] ZRVList
        {
            get
            {
                return this.zRVListField;
            }
            set
            {
                this.zRVListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZHS", IsNullable = false)]
        public TZHS_ZHPO[] ZHSList
        {
            get
            {
                return this.zHSListField;
            }
            set
            {
                this.zHSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZUS", IsNullable = false)]
        public TZUSO[] ZUSList
        {
            get
            {
                return this.zUSListField;
            }
            set
            {
                this.zUSListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZZP", IsNullable = false)]
        public TZZP_ZZOO[] ZZPList
        {
            get
            {
                return this.zZPListField;
            }
            set
            {
                this.zZPListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZPB", IsNullable = false)]
        public TZPB_ZPNO[] ZPBList
        {
            get
            {
                return this.zPBListField;
            }
            set
            {
                this.zPBListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZDC", IsNullable = false)]
        public TZDC_ZDDO[] ZDCList
        {
            get
            {
                return this.zDCListField;
            }
            set
            {
                this.zDCListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZUD", IsNullable = false)]
        public TZUD_ZUNO[] ZUDList
        {
            get
            {
                return this.zUDListField;
            }
            set
            {
                this.zUDListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TPOVO
    {

        private string nuField;

        private System.Nullable<int> koField;

        private System.Nullable<System.DateTime> acField;

        private TZZV_ZZDO[] zZVListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NU
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> KO
        {
            get
            {
                return this.koField;
            }
            set
            {
                this.koField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> AC
        {
            get
            {
                return this.acField;
            }
            set
            {
                this.acField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ZZV", IsNullable = false)]
        public TZZV_ZZDO[] ZZVList
        {
            get
            {
                return this.zZVListField;
            }
            set
            {
                this.zZVListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public partial class TUES
    {

        private string poField;

        private string tiField;

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string TI
        {
            get
            {
                return this.tiField;
            }
            set
            {
                this.tiField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransEnvTypeIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    public abstract partial class TransEnvelopeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0")]
    [System.Xml.Serialization.XmlRootAttribute("TransEnvOut", Namespace = "http://www.egov.sk/mvsr/RFO/Podp/Ext/ZoznamIFOSoZmenenymiReferencnymiUdajmiWS-v1." +
        "0", IsNullable = false)]
    public partial class TransEnvTypeOut : TransEnvelopeType
    {

        private TPOVO pOVField;

        private string corrIDField;

        /// <remarks/>
        public TPOVO POV
        {
            get
            {
                return this.pOVField;
            }
            set
            {
                this.pOVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string corrID
        {
            get
            {
                return this.corrIDField;
            }
            set
            {
                this.corrIDField = value;
            }
        }
    }
}
